[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Go-kart"
authors = [{name = "XLAB", email = "xlabupenn@gmail.com"}]
dynamic = ["version", "description"]
